### ISSUE TITLE
😥 Ground isn't moving

### ISSUE THREAD

**Issue by Pakodawala** [VerySmort/AiCovidProject#10]
![%t 20 16 -30 07 21209](https://user-images.githubusercontent.com/88194153/127670505-db686af3-3b26-435b-874d-58b8c8769d30.gif)

 Have to do something big fast!!

**Comment by Pakodawala** [comment]
maybe make ground smooth?

**Comment by VerySmort** [comment]
ok

**Comment by Pakodawala** [comment]
@VerySmort do it if you can

**Comment by Pakodawala** [comment]
wont fix
